import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'},
    {
      type: 'link',
      label: 'ha with us on Discordhaha',
      href: 'https://discord.gg/docusaurus',
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  ailbasis: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      href: '/changelog',
      label: 'Changelog',
    },
    {
      type: 'link',
      href: '/showcase',
      label: 'Showcase',
    },
    {
      type: 'link',
      href: '/feature-requests',
      label: 'Feature Requests',
    },
    {
      type: 'link',
      label: 'haha with us on Discordhaha',
      href: 'https://discord.gg/docusaurus',
    },
  ],

  mySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar slice from docs/api
    },
    {
      type: 'link',
      label: 'hahah with us on Discordhaha',
      href: 'https://discord.gg/docusaurus',
    },

  ],

};

export default sidebars;
